[package]
name = "esp32s3_box"
version = "0.1.0"
authors = ["Samuel Benko <samuel.benko@espressif.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32s3-hal = "0.4.0"
esp-alloc = { version = "0.1.0", features = ["oom-handler"] }
esp-backtrace = { version = "0.4.0", features = ["esp32s3", "panic-handler", "print-uart"] }
xtensa-lx-rt = { version = "0.14.0", features = ["esp32s3"], optional = true }
esp-println = { version = "0.3.1", features = [ "esp32s3" ] }
embedded-graphics = "0.7"
mipidsi = { git = "https://github.com/almindor/mipidsi" }
display-interface-spi = "0.4"
embedded-graphics-framebuf = "0.2.0"

#rustmas dependencies
libm = "0.2.5"
tinybmp = "0.4.0"
examples-assets = { path = "./examples-assets"}

[features]
default = ["rt"]
rt = ["xtensa-lx-rt"]
